"""customer_invoices delivery_id and pdf_storage_uri

Revision ID: 53b424ccc914
Revises: 5806281e2f67
Create Date: 2026-08-25 13:10:18.728902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b424ccc914'
down_revision: Union[str, Sequence[str], None] = '5806281e2f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_invoices', sa.Column('delivery_id', sa.UUID(), nullable=True))
    op.add_column('customer_invoices', sa.Column('pdf_storage_uri', sa.String(length=500), nullable=True))
    op.create_unique_constraint('uq_customer_invoices_delivery_id', 'customer_invoices', ['delivery_id'])
    op.create_foreign_key(
        'fk_customer_invoices_delivery_id_deliveries',
        'customer_invoices', 'deliveries', ['delivery_id'], ['id'], ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_customer_invoices_delivery_id_deliveries', 'customer_invoices', type_='foreignkey')
    op.drop_constraint('uq_customer_invoices_delivery_id', 'customer_invoices', type_='unique')
    op.drop_column('customer_invoices', 'pdf_storage_uri')
    op.drop_column('customer_invoices', 'delivery_id')
    # ### end Alembic commands ###
