"""outbox events last_attempted_at

Revision ID: 5806281e2f67
Revises: 8b65642f38cf
Create Date: 2026-08-24 10:53:59.743899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5806281e2f67'
down_revision: Union[str, Sequence[str], None] = '8b65642f38cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'last_attempted_at')
    # ### end Alembic commands ###
