"""hot query partial indexes

Revision ID: a7f7f37cff94
Revises: c194c1c9bd9f
Create Date: 2026-08-22 12:32:55.603312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f7f37cff94'
down_revision: Union[str, Sequence[str], None] = 'c194c1c9bd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_approvals_pending', 'approvals', ['org_id', 'sla_due_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_customer_invoices_unpaid', 'customer_invoices', ['org_id', 'due_date'], unique=False, postgresql_where=sa.text("status NOT IN ('paid', 'void')"))
    op.create_index('ix_notifications_pending', 'notifications', ['org_id', 'created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_outbox_events_unpublished', 'outbox_events', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_index('ix_purchase_orders_open', 'purchase_orders', ['org_id'], unique=False, postgresql_where=sa.text("status NOT IN ('received', 'invoiced', 'paid', 'cancelled')"))
    op.create_index('ix_purchase_requisitions_pending_approval', 'purchase_requisitions', ['org_id'], unique=False, postgresql_where=sa.text("status = 'pending_approval'"))
    op.create_index('ix_sales_orders_open', 'sales_orders', ['org_id', 'order_date'], unique=False, postgresql_where=sa.text("status NOT IN ('invoiced', 'cancelled')"))
    op.create_index('ix_supplier_invoices_actionable', 'supplier_invoices', ['org_id', 'due_date'], unique=False, postgresql_where=sa.text("status NOT IN ('paid')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_invoices_actionable', table_name='supplier_invoices', postgresql_where=sa.text("status NOT IN ('paid')"))
    op.drop_index('ix_sales_orders_open', table_name='sales_orders', postgresql_where=sa.text("status NOT IN ('invoiced', 'cancelled')"))
    op.drop_index('ix_purchase_requisitions_pending_approval', table_name='purchase_requisitions', postgresql_where=sa.text("status = 'pending_approval'"))
    op.drop_index('ix_purchase_orders_open', table_name='purchase_orders', postgresql_where=sa.text("status NOT IN ('received', 'invoiced', 'paid', 'cancelled')"))
    op.drop_index('ix_outbox_events_unpublished', table_name='outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_index('ix_notifications_pending', table_name='notifications', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_customer_invoices_unpaid', table_name='customer_invoices', postgresql_where=sa.text("status NOT IN ('paid', 'void')"))
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_approvals_pending', table_name='approvals', postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###
